### ISSUE TITLE
[Meta] Pilot Flows

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#103]
Meta issue to hold reference to the required user flows through the pilot.

- [ ] Registration
- [ ] Creating a new project
- [ ] Inviting other users
  - [ ] Internal
  - [ ] External
- [ ] Requesting resources
  - [ ] With metadata complete
  - [ ] With metadata incomplete
- [ ] Project metadata
- [ ] Submitting feedback
- [ ] Datahub admin project approval
