### ISSUE TITLE
As a registered user, I want the portal to meet i18n standards so that I can use my language of choice

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#114]
## Tasks

- [ ] Identify translation flow for new content
- [ ] Verify a translation exists for all content
- [ ] Validate the translations for both languages

## Supporting Documentation

On Request
