### ISSUE TITLE
🧩 Smoke tests for deployment

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#215]
## Tasks
- [x] #216
- [x] Create health queue ping for each function
- [ ] Create poison queue checks
- [ ] Create health check for resource deployment
