### ISSUE TITLE
[Meta] Initial user flow issue tracking

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#237]
- [x] Update home page with new user project view
- [x] Remove Admin Actions, Storage Cost Estimator, and Compute Cost Estimator from Active Tools section
- [x] Remove Public Data Sharing and Power BI Workspace from Available Tool section
- [x] Fix icons for Databricks Notebooks and Workspace Storage
- [x] #270
- [x] Update project members section (see main tracking issue #102)
- [x] Show that project is still waiting for Admin Approval (waiting on PR approval)
- [x] Disable Resource creation until approved
- [x] Determine if need organization name when creating project or if able to update later
- [x] #277
- [x] point read more link to `resources/fr?/title`
- [x] add listener to update project status
- [x] add listener logic to update storage status
- [x] stop copying .md files in provisioner
- [x] #255
- [x] active storage resource card
