### ISSUE TITLE
Improve project costing

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#337]
Leverage the costing data generated by NRC in the Azure Portal to display new costing info in a project.

## Tasks
- [x] #427
- [x] Bug: current costing function is not running properly, was it deployed? is it running?
- [x] Convert costing function to save every detail from consumption api in table
- [x] Create aggregate table off the details table
- [x] #496

**Comment by yjmrobert** [comment]
@iroelperez can we close this? or soon?
